name: sync2mirror
on:
  push:
    branches:
      - master
      - dev
jobs:
  repo-sync:
    env:
      gitee_key: ${{ secrets.GITEE_PRIVATE_KEY }}
      gitee_token: ${{ secrets.GITEE_TOKEN }}
      gitee_user: ${{ secrets.GITEE_USER }}
      gitcode_key: ${{ secrets.GITCODE_PRIVATE_KEY }}
      gitcode_token: ${{ secrets.GITCODE_TOKEN }}
      gitcode_user: ${{ secrets.GITCODE_USER }}
      gitcode_key_2: ${{ secrets.GITCODE_PRIVATE_KEY_1 }}
      gitcode_token_2: ${{ secrets.GITCODE_TOKEN_2 }}
      gitcode_user_2: ${{ secrets.GITCODE_USER_2 }}
      gitcode_key_3: ${{ secrets.GITCODE_PRIVATE_KEY_2 }}
      gitcode_token_3: ${{ secrets.GITCODE_TOKEN_1 }}
      gitcode_user_3: ${{ secrets.GITCODE_USER_1 }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync github -> gitee
        uses: Yikun/hub-mirror-action@master
        if: env.gitee_key && env.gitee_token && env.gitee_user
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitee/${{ secrets.GITEE_USER }}'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          static_list: ${{ github.event.repository.name }}
          mappings: "AzurLaneAutoScript=>AzurLaneAutoScript1"
          force_update: true

      - name: sync github -> gitcode
        uses: Yikun/hub-mirror-action@master
        if: env.gitcode_key && env.gitcode_token && env.gitcode_user
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitcode/${{ secrets.GITCODE_USER }}'
          dst_key: ${{ secrets.GITCODE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITCODE_TOKEN }}
          account_type: user
          static_list: ${{ github.event.repository.name }}
          mappings: "AzurLaneAutoScript=>AzurLaneAutoScript"
          force_update: true

      - name: sync github -> gitcode2
        uses: Yikun/hub-mirror-action@master
        if: env.gitcode_key_2 && env.gitcode_token_2 && env.gitcode_user_2
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitcode/${{ secrets.GITCODE_USER_2 }}'
          dst_key: ${{ secrets.GITCODE_PRIVATE_KEY_1 }}
          dst_token: ${{ secrets.GITCODE_TOKEN_2 }}
          account_type: user
          static_list: ${{ github.event.repository.name }}
          mappings: "AzurLaneAutoScript=>AzurLaneAutoScript"
          force_update: true
      
      - name: sync github -> gitcode3
        uses: Yikun/hub-mirror-action@master
        if: env.gitcode_key_3 && env.gitcode_token_3 && env.gitcode_user_3
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitcode/${{ secrets.GITCODE_USER_1 }}'
          dst_key: ${{ secrets.GITCODE_PRIVATE_KEY_2 }}
          dst_token: ${{ secrets.GITCODE_TOKEN_1 }}
          account_type: user
          static_list: ${{ github.event.repository.name }}
          mappings: "AzurLaneAutoScript=>AzurLaneAutoScript"
          force_update: true